### ISSUE TITLE
[new module] Navigation

### ISSUE THREAD

**Issue by acelaya** [sitrunlab/LearnZF2#102]

**Comment by samsonasik** [comment]
@acelaya do you work on it ?

**Comment by acelaya** [comment]
I've been a little busy with work stuff lately. 
I'll probably have some time this weekend.

**Comment by samsonasik** [comment]
It's ok, thank you very much ;)

Warm Regards,

Abdul Malik Ikhsan


2015-02-27 1:36 GMT+07:00 Alejandro Celaya <notifications@github.com>:

**Comment by samsonasik** [comment]
implemented by #117
