### ISSUE TITLE
[new module] Permission ( ACL )

### ISSUE THREAD

**Issue by samsonasik** [sitrunlab/LearnZF2#114]

**Comment by samsonasik** [comment]
I will try to do it in weekend ;)

**Comment by samsonasik** [comment]
I've created wireframe for it like the following image : 
![wireframe-acl](https://cloud.githubusercontent.com/assets/459648/6657713/4f59c2e8-cb86-11e4-9ee1-156575e4fbc8.png)

**Comment by acelaya** [comment]
Looks good

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
sorry for the delay, been very busy this week, I will do it when I have time

**Comment by samsonasik** [comment]
I've created PR #118 for it.

**Comment by samsonasik** [comment]
implemented by #118
