### ISSUE TITLE
New module. LearnZF2AjaxFormGallery

### ISSUE THREAD

**Issue by Stanimirdim92** [sitrunlab/LearnZF2#132]
Currently I'm creating an ajax gallery for my own CMS - something like wordpress uplaod gallery, but better ;). After I finish it I will finish the tutorial here. Ideas a welcome.

Regards,
Stanimir

**Comment by samsonasik** [comment]
Thanks. Will be more great if the tutorial module related with specific component, like using Zend\Progressbar for upload ;)

Warm regards,

Abdul Malik Ikhsan

Pada 19 Mei 2015, pukul 20.59, Stanimir Dimitrov <notifications@github.com> menulis:

**Comment by Stanimirdim92** [comment]
I tried to work with Zend\Progressbar, but never managed to gt it working. I think it's broken or I'm too stupid. Any good tutorial?

**Comment by samsonasik** [comment]
No, lol :D, but probably it can be starting https://github.com/zendframework/zf2/tree/master/demos/Zend/ProgressBar

**Comment by Stanimirdim92** [comment]
Does anyone knows/have a cross browser solution for file upload in IE<9, without using iframe? I know that I can download a plugin or something, but I don't want to do it for now.

**Comment by acelaya** [comment]
If you want an asynchronous upload, I'm afraid there is no way to do it
other than using an iframe.

**Comment by Stanimirdim92** [comment]
I'm leaving this todo list here as a reminder to me.

TODO:
- Add Zend/Filter/ProgressBar
- Create an image thumbnail/crop classes that's implement interfaces and works with GD and ImageShack libraries from PHP or use Imagine module.
- Image edit settings such as: width, height, rename

WIP:
- Better gallery view. Current one is like the one from Windows, when you view many images from a folder. Grid with all the images from the left side and bigger view of the selected from the right side. Maybe add fancybox?
- Better handling of success/error messages for each uploaded image.


DONE:
- Uploading works in separated folders for each month. path/date("Y_m")/
- Using echo Json::encode() without JsonModel in order to return the json. :(
- After image upload, redirect to the gallery view and load all images from all folders. For the iteration of the folders I use the RecursiveDirectoryIterator combined with RecursiveIteratorIterator.
- Validate the uploaded files. Using IsImage, Extension and Size classes. No Javascript validation!

**Comment by samsonasik** [comment]
Thank yoiu. Would be great if you could make a [wip] pull request so we can review early during you develop it.

Warm regards,

Abdul Malik Ikhsan

Pada 2 Jun 2015, pukul 23.47, Stanimir Dimitrov <notifications@github.com> menulis:

**Comment by Stanimirdim92** [comment]
Sure, but not right now. I want to finish few more things and polish some other. Will do it as soon as I can.

**Comment by Stanimirdim92** [comment]
I have manage to graduate today. From tomorrow or the day after that I'm going to focus on this module and many others. 

Btw, check this website. http://learnzf.com/ o_0

**Comment by samsonasik** [comment]
Congratulations! Enjoy ;)
Oh, yeah, that site :p

Warm regards,

Abdul Malik Ikhsan

Pada 14 Jul 2015, pukul 00.04, Stanimir Dimitrov <notifications@github.com> menulis:

**Comment by Stanimirdim92** [comment]
It's been ages since I posted here, lol. :D An update is coming these days, but I stumbled on an encoding problem. For example: if I have an image with name my_image_name - Копие where "Копие" is on Bulgarian, the system can't find the image inside the upload folder due to the encoding bug. So at the end I end up with my_image_name - РљРѕРїРёРµ.png

Suggestions?

**Comment by samsonasik** [comment]
it's ok ;). probably you use `Zend\Filter\File\RenameUpload` ? for ex: https://github.com/cgmartin/ZF2FileUploadExamples/blob/master/src/ZF2FileUploadExamples/Form/SingleUpload.php#L43

**Comment by Stanimirdim92** [comment]
Closing this in favour of https://github.com/sitrunlab/LearnZF2/pull/136
