### ISSUE TITLE
Free SitrunLab T-shirt

### ISSUE THREAD

**Issue by samsonasik** [sitrunlab/LearnZF2#133]
Hi,

First of all, thank you for all the contributions for this repository. I'm planning to make a T-shirt and give away to you. This is the design : 
![sitrun-lab-shirt](https://cloud.githubusercontent.com/assets/459648/7761667/c1cab5d4-0052-11e5-8aea-df787fad2ce4.jpg)
If you like it, please give me the complete name and address to my email ( samsonasik@gmail.com ), so when it done, I can send to your address.

Thank you.

**Comment by samsonasik** [comment]
and the size ( S - M - L )

**Comment by acelaya** [comment]
Cool!! Thank you @samsonasik!
I'll send you my address this afternoon.

**Comment by Stanimirdim92** [comment]
Count me in. I will send you the information tonight.

Question: What about putting LearnZF2 logo/text as well :)

**Comment by samsonasik** [comment]
Thanks, 
Answer : well, LearnZF2 doesn't have logo now ;), so probably not yet ;)

Warm regards,

Abdul Malik Ikhsan

Pada 22 Mei 2015, pukul 18.49, Stanimir Dimitrov <notifications@github.com> menulis:

**Comment by samsonasik** [comment]
hm..., I probably can add sitrunlab repository link then

Warm regards,

Abdul Malik Ikhsan

Pada 22 Mei 2015, pukul 18.49, Stanimir Dimitrov <notifications@github.com> menulis:

**Comment by mockiemockiz** [comment]
do you want another design? i will design it, not the complex one and I can't guarantee it will be better than your.. but if you want another option, i will design it this weekend.

**Comment by samsonasik** [comment]
that will be great ;). I've sent you the .psd for reference. Thank you.

Warm Regards,

Abdul Malik Ikhsan


2015-05-22 19:39 GMT+07:00 muhamad rifki <notifications@github.com>:

**Comment by samsonasik** [comment]
@mockiemockiz any update for your suggested design?

**Comment by samsonasik** [comment]
Hi All, 
I'm so sorry for it, seems not going to be happen
it is very expensive to create t-shirt in few order here, that was my fault because I didn't check about that first ...

**Comment by acelaya** [comment]
Don't worry ;-)

--
Alejandro Celaya Alastrué
