### ISSUE TITLE
Captha module

### ISSUE THREAD

**Issue by samsonasik** [sitrunlab/LearnZF2#135]
I've idea for captcha sample module.

**Comment by samsonasik** [comment]
the idea is user can select types of captcha, and show/validate it.

**Comment by acelaya** [comment]
Good idea.

2015-06-03 18:18 GMT+02:00 Abdul Malik Ikhsan <notifications@github.com>:

> the idea is user can select types of captcha, and show/validate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sitrunlab/LearnZF2/issues/135#issuecomment-108508403>.
>



-- 
Alejandro Celaya Alastrué
http://www.alejandrocelaya.com

**Comment by Stanimirdim92** [comment]
Go for it!

2015-06-03 19:41 GMT+03:00 Alejandro Celaya <notifications@github.com>:

**Comment by samsonasik** [comment]
I will ;)
