### ISSUE TITLE
using phpspec/prophecy for mocking

### ISSUE THREAD

**Issue by samsonasik** [sitrunlab/LearnZF2#138]
see https://samsonasik.wordpress.com/2015/08/29/testing-zend-framework-2-factory-using-prophecy/ . I think it can simplify the tests ;)

**Comment by acelaya** [comment]
Sure!

**Comment by samsonasik** [comment]
@acelaya ok, I created #139 for it. The tests that still need to be updated is tests for `Application\Module` and `LearnZF2I18n\Module` .

**Comment by samsonasik** [comment]
prophecy for `Application\Module` tests has been implemented. now need to implement `LearnZF2I18n\Module` tests to be `prophesized`, @acelaya could you help? Thanks ^^

**Comment by acelaya** [comment]
Yes, I'll try to do it this afternoon ;-)

--
Alejandro Celaya Alastrué

**Comment by Stanimirdim92** [comment]
Sorry, for the late answer. Been busy with life and the system. Will have a look at this tomorrow.

**Comment by acelaya** [comment]
I'll porobably won't be finally able to do it until weekend

2015-09-03 21:05 GMT+02:00 Stanimir Dimitrov <notifications@github.com>:

> Sorry, for the late answer. Been busy with life and the system. Will have
> a look at this tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sitrunlab/LearnZF2/issues/138#issuecomment-137543832>.
>



-- 
Alejandro Celaya Alastrué
http://www.alejandrocelaya.com

**Comment by samsonasik** [comment]
it's ok ;)

**Comment by acelaya** [comment]
Just opened the pull request to implement this on the i18n module #140
