### ISSUE TITLE
Server upgraded to PHP 5.5

### ISSUE THREAD

**Issue by samsonasik** [sitrunlab/LearnZF2#141]
The PHP version of the site has been upgraded to 5.5. Can we can use ZF ~2.5.0 then? Or just use ~2.4.0 as it is long term support? there are tests that need to be updated if we upgrade ZF to ~2.5.0.

**Comment by Stanimirdim92** [comment]
I say let's go with 5.5. Wouldn't e harder t upgrade to ZF3 from 2.4+?

**Comment by samsonasik** [comment]
yup, not sure about zf3 yet, may be we need to have LearnZF3 instead, but actually don't know about current ZF3 will improve
