### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by Stanimirdim92** [sitrunlab/LearnZF2#142]
Hi,

I have been playin with gulp for the last 3 days and I have to say it's wayyyyyyyyyy better than Grunt. I have setup a gulp script for my system for the new assets structure which has few depth levels and different directories for every type of file including prod and dev files/folders. So I was thinking maybe we can setup such envioment for this project as well? This is my scripts incase you want to have a look at the code. https://gist.github.com/Stanimirdim92/cd58ea35da1277b3084c

**Comment by samsonasik** [comment]
I currently don't have idea about this tool. You can try it, modify the .travis.yml to run grunt and see what it will happen in PR?

**Comment by Stanimirdim92** [comment]
http://gulpjs.com/ It's different from Grunt since gulp is using nodejs streams via pipes to run all it's tasks. Can I play with the design as well? :D

**Comment by samsonasik** [comment]
of course yes. you can make more PRs for different / sub task to make not quite big PR to make more review-able/ merge-able.

**Comment by Stanimirdim92** [comment]
Closing this for now. I don't have the time needed to create new website architecture nor design.

**Comment by samsonasik** [comment]
it's ok, thank you ;)
