### ISSUE TITLE
Theme switcher

### ISSUE THREAD

**Issue by Stanimirdim92** [sitrunlab/LearnZF2#156]
I'm going to create a theme switcher module.

**Comment by samsonasik** [comment]
require 3rd party module?

**Comment by Stanimirdim92** [comment]
Nope. All built with ZF2. 

The way I made it is this:
- Created Themes module. Inside there is a Module.php with getConfig method. The other folders are the names of the themes required for the CMS such as . default, awesome etc etc
- Inside these themes I store a config folder with module.config.php which contents is only this;

return [
    /**
     * These are mandatory as well, but if anyone don't want to put text, just leave them empty: => ''
     */
    'description' => 'Application default theme that comes with the installation',
    'title' => 'Default',
    'screenshot' => 'default.png',
    'author' => 'Stanimir Dimitrov',

    /**
     * The only path structure that is a must and must stay this way is /themes/THEME_NAME/.
     * /themes/THEME_NAME/ is built automatically by the system.
     *
     * Every other file structure can be orginized according to the users needs.
     * Which means that these examples are fully valid.
     *
     * You can omit the first trailing slash. The system will always include one for you.
     *
     *
     *   'css' => [
     *       '/habalababala/Anotherpath/to/style.css',
     *       'css/style.css',
     *       'scss/style.css',
     *       '/css/scss/style.css',
     *   ],
     *   'js' => [
     *       '/habalababala/Anotherpath/to/custom.js',
     *       '/assets//js/ember.js',
     *       '3rdparty/jquery.js',
     *    ],
     *
     */
    'css' => [
        '/front/css/front.min.css',
    ],
    'js' => [
        '/front/js/front.min.js',
    ],

    /**
     * This is not necessary, but it's good for performance.
     */
    'template_map' => include __DIR__.'/../template_map.php',
    'template_path_stack' => [
        'default' => __DIR__.'/../view',
    ],
];

- There is also a view folder with all the phtml files. and a template_map. All the assets such as css,js, images is stored inside the public/themes/THEME_NAME folder. and ae being called in the html ONLY when the theme is loaded.
- Inside Application module I have a factory initThemes which calls the theme name from serviceLocator->get("Config") and loads it from onBootstrap method with a render event listener.
- All theme configs are also stored inside serviceLocator->get("Config")  via the themes key.

Suggestions are welcome.

**Comment by samsonasik** [comment]
I personally think it's too complicated, even user to install, too many steps will be required to get it working, also, we need to have module that shows the power of zf2, like #157 ( controller plugin ), user can just download, paste in module, and run it. I am against about "Admin" module as we need a "single easy module" to be picked and try.

**Comment by Stanimirdim92** [comment]
It only sounds complicated. Also, there won't be an admin module here. I was refering to my CMS. Give me a day for the first drafts.

**Comment by samsonasik** [comment]
ok :+1:

**Comment by Stanimirdim92** [comment]
Module done. Closing.
