### ISSUE TITLE
Add ajax upload example to LearnAjax Module

### ISSUE THREAD

**Issue by mockiemockiz** [sitrunlab/LearnZF2#49]
As soon as possible.

**Comment by mockiemockiz** [comment]
I got bump in my ear and need more time to think how I can get money to do surgery.. I'm sorry if this module is being abandoned. by the way I removed my facebook and twitter account, so hope you both @samsonasik  and @acelaya don't get me wrong if you can find me there. Thanks!

**Comment by samsonasik** [comment]
@mockiemockiz i'm sorry to hear that, hope everything will be fine. it's ok, take your time ...

**Comment by acelaya** [comment]
Take care @mockiemockiz, and don't worry about the module, we'll finish it.
