### ISSUE TITLE
Download Counter

### ISSUE THREAD

**Issue by samsonasik** [sitrunlab/LearnZF2#53]
Need download counter to be saved to file to check how people really want to download the modules.

**Comment by samsonasik** [comment]
is it applicable ? or any other idea ?

**Comment by acelaya** [comment]
I think it's good this way.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
which/what way?

**Comment by acelaya** [comment]
Sorry :) 
We already have a mysql database and the DoctrineORMModule, so I think that's the good approach.

**Comment by samsonasik** [comment]
it's ok, I will try to create wireframe and db structure for it ;)
