### ISSUE TITLE
Adding credit links to icon maker's website.

### ISSUE THREAD

**Issue by mockiemockiz** [sitrunlab/LearnZF2#63]
Adding links to icon maker's website 
https://github.com/sitrunlab/LearnZF2/blob/develop/public/img/licenses.txt

Where should I put this ? footer? or should I provide box in the sidebar to provides links ( including contributors' link websites.

**Comment by samsonasik** [comment]
I created PR #93 for it ;)

**Comment by samsonasik** [comment]
Fixed by #93
