### ISSUE TITLE
improve phpunit unit tests again

### ISSUE THREAD

**Issue by samsonasik** [sitrunlab/LearnZF2#79]

**Comment by samsonasik** [comment]
@acelaya any update for this?

**Comment by acelaya** [comment]
Sorry, I wasn't able to work on this yet. I planned to do it today or
tomorrow.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
it is ok, thank you ;)

**Comment by acelaya** [comment]
@samsonasik I'm not probably going to have the time to work on this until January 14th. Is that a problem?

**Comment by samsonasik** [comment]
@acelaya it's ok , take your time. ;)

**Comment by samsonasik** [comment]
@acelaya any update for this ?

**Comment by acelaya** [comment]
Yes, I started to work on it yesterday.
I'll probably have it done this week.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
@acelaya thank you ;)
